---
development:
  dialect: "mysql"
  database: "crowddefensewebsite_development"
  host: "beemo.at"
  port: "3307"
  user: "crowddefense_dev"
  password: "x5nZf%J9wFAnB*#zZEFh%bkabbAQ^FQir^6xidyM*x^JW54e54czVZ*hpAXih^5t"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://mysql:mysql@127.0.0.1:5432/crowddefensewebsite_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://mysql:mysql@127.0.0.1:5432/crowddefensewebsite_production?sslmode=disable"}}
